# Generated by Django 4.2.2 on 2023-06-21 11:50

import autoslug.fields
from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=main.models.slugify_func, unique=True),
        ),
    ]
